/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignageRouteImport } from './routes/signage'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ReengajamentoRouteImport } from './routes/reengajamento'
import { Route as MeuFinanceiroRouteImport } from './routes/meu-financeiro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FilaEsperaRouteImport } from './routes/fila-espera'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComandaRouteImport } from './routes/comanda'
import { Route as BarbeirosRouteImport } from './routes/barbeiros'
import { Route as AssinaturasRouteImport } from './routes/assinaturas'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignageTvRouteImport } from './routes/signage_.tv'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as BSlugAgendarRouteImport } from './routes/b.$slug.agendar'
import { Route as ApiPublicMercadopagoRouteImport } from './routes/api/public/mercadopago'

const SignageRoute = SignageRouteImport.update({
  id: '/signage',
  path: '/signage',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReengajamentoRoute = ReengajamentoRouteImport.update({
  id: '/reengajamento',
  path: '/reengajamento',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuFinanceiroRoute = MeuFinanceiroRouteImport.update({
  id: '/meu-financeiro',
  path: '/meu-financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FilaEsperaRoute = FilaEsperaRouteImport.update({
  id: '/fila-espera',
  path: '/fila-espera',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandaRoute = ComandaRouteImport.update({
  id: '/comanda',
  path: '/comanda',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbeirosRoute = BarbeirosRouteImport.update({
  id: '/barbeiros',
  path: '/barbeiros',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturasRoute = AssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignageTvRoute = SignageTvRouteImport.update({
  id: '/signage_/tv',
  path: '/signage/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugAgendarRoute = BSlugAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => BSlugRoute,
} as any)
const ApiPublicMercadopagoRoute = ApiPublicMercadopagoRouteImport.update({
  id: '/api/public/mercadopago',
  path: '/api/public/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/assinaturas': typeof AssinaturasRoute
  '/barbeiros': typeof BarbeirosRoute
  '/comanda': typeof ComandaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/fila-espera': typeof FilaEsperaRoute
  '/login': typeof LoginRoute
  '/meu-financeiro': typeof MeuFinanceiroRoute
  '/reengajamento': typeof ReengajamentoRoute
  '/servicos': typeof ServicosRoute
  '/signage': typeof SignageRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/signage/tv': typeof SignageTvRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
  '/b/$slug/agendar': typeof BSlugAgendarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/assinaturas': typeof AssinaturasRoute
  '/barbeiros': typeof BarbeirosRoute
  '/comanda': typeof ComandaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/fila-espera': typeof FilaEsperaRoute
  '/login': typeof LoginRoute
  '/meu-financeiro': typeof MeuFinanceiroRoute
  '/reengajamento': typeof ReengajamentoRoute
  '/servicos': typeof ServicosRoute
  '/signage': typeof SignageRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/signage/tv': typeof SignageTvRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
  '/b/$slug/agendar': typeof BSlugAgendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/assinaturas': typeof AssinaturasRoute
  '/barbeiros': typeof BarbeirosRoute
  '/comanda': typeof ComandaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/fila-espera': typeof FilaEsperaRoute
  '/login': typeof LoginRoute
  '/meu-financeiro': typeof MeuFinanceiroRoute
  '/reengajamento': typeof ReengajamentoRoute
  '/servicos': typeof ServicosRoute
  '/signage': typeof SignageRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/signage_/tv': typeof SignageTvRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
  '/b/$slug/agendar': typeof BSlugAgendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/assinaturas'
    | '/barbeiros'
    | '/comanda'
    | '/configuracoes'
    | '/dashboard'
    | '/fila-espera'
    | '/login'
    | '/meu-financeiro'
    | '/reengajamento'
    | '/servicos'
    | '/signage'
    | '/b/$slug'
    | '/signage/tv'
    | '/api/public/mercadopago'
    | '/b/$slug/agendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/assinaturas'
    | '/barbeiros'
    | '/comanda'
    | '/configuracoes'
    | '/dashboard'
    | '/fila-espera'
    | '/login'
    | '/meu-financeiro'
    | '/reengajamento'
    | '/servicos'
    | '/signage'
    | '/b/$slug'
    | '/signage/tv'
    | '/api/public/mercadopago'
    | '/b/$slug/agendar'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/assinaturas'
    | '/barbeiros'
    | '/comanda'
    | '/configuracoes'
    | '/dashboard'
    | '/fila-espera'
    | '/login'
    | '/meu-financeiro'
    | '/reengajamento'
    | '/servicos'
    | '/signage'
    | '/b/$slug'
    | '/signage_/tv'
    | '/api/public/mercadopago'
    | '/b/$slug/agendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AssinaturasRoute: typeof AssinaturasRoute
  BarbeirosRoute: typeof BarbeirosRoute
  ComandaRoute: typeof ComandaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  FilaEsperaRoute: typeof FilaEsperaRoute
  LoginRoute: typeof LoginRoute
  MeuFinanceiroRoute: typeof MeuFinanceiroRoute
  ReengajamentoRoute: typeof ReengajamentoRoute
  ServicosRoute: typeof ServicosRoute
  SignageRoute: typeof SignageRoute
  BSlugRoute: typeof BSlugRouteWithChildren
  SignageTvRoute: typeof SignageTvRoute
  ApiPublicMercadopagoRoute: typeof ApiPublicMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signage': {
      id: '/signage'
      path: '/signage'
      fullPath: '/signage'
      preLoaderRoute: typeof SignageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reengajamento': {
      id: '/reengajamento'
      path: '/reengajamento'
      fullPath: '/reengajamento'
      preLoaderRoute: typeof ReengajamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-financeiro': {
      id: '/meu-financeiro'
      path: '/meu-financeiro'
      fullPath: '/meu-financeiro'
      preLoaderRoute: typeof MeuFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fila-espera': {
      id: '/fila-espera'
      path: '/fila-espera'
      fullPath: '/fila-espera'
      preLoaderRoute: typeof FilaEsperaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comanda': {
      id: '/comanda'
      path: '/comanda'
      fullPath: '/comanda'
      preLoaderRoute: typeof ComandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbeiros': {
      id: '/barbeiros'
      path: '/barbeiros'
      fullPath: '/barbeiros'
      preLoaderRoute: typeof BarbeirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinaturas': {
      id: '/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signage_/tv': {
      id: '/signage_/tv'
      path: '/signage/tv'
      fullPath: '/signage/tv'
      preLoaderRoute: typeof SignageTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug/agendar': {
      id: '/b/$slug/agendar'
      path: '/agendar'
      fullPath: '/b/$slug/agendar'
      preLoaderRoute: typeof BSlugAgendarRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/api/public/mercadopago': {
      id: '/api/public/mercadopago'
      path: '/api/public/mercadopago'
      fullPath: '/api/public/mercadopago'
      preLoaderRoute: typeof ApiPublicMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BSlugRouteChildren {
  BSlugAgendarRoute: typeof BSlugAgendarRoute
}

const BSlugRouteChildren: BSlugRouteChildren = {
  BSlugAgendarRoute: BSlugAgendarRoute,
}

const BSlugRouteWithChildren = BSlugRoute._addFileChildren(BSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AssinaturasRoute: AssinaturasRoute,
  BarbeirosRoute: BarbeirosRoute,
  ComandaRoute: ComandaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  FilaEsperaRoute: FilaEsperaRoute,
  LoginRoute: LoginRoute,
  MeuFinanceiroRoute: MeuFinanceiroRoute,
  ReengajamentoRoute: ReengajamentoRoute,
  ServicosRoute: ServicosRoute,
  SignageRoute: SignageRoute,
  BSlugRoute: BSlugRouteWithChildren,
  SignageTvRoute: SignageTvRoute,
  ApiPublicMercadopagoRoute: ApiPublicMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
